targets:
  $default:
    builders:
      graphql_codegen:
        generate_for:
          - lib/*.graphql
        options:
          outputDirectory: generated
          clients:
            - graphql
            - graphql_flutter # we need this for hooks
